module.exports = function(bcrypt, app_cfg) {

  // TODO: gegen better-sqlite3 ersetzen

  // Datenbank einrichten
  const sqlite3 = require('sqlite3').verbose();
  var fs = require('fs');
  var dbFile = app_cfg.global.database;
  var dbExists = fs.existsSync(dbFile);

  // Datenbank erstellen
  var db = new sqlite3.Database(dbFile, sqlite3.OPEN_READWRITE, (err) => {
    if (err) {
      console.error(err.message);
    }
    db.run('PRAGMA foreign_keys=on');
  });

  // Datenbank bei Neustart bereinigen, oder Datenbank befuellen
  if (dbExists) {
    db.serialize(function() {
      // alte Clients (Sockets) bei neustart des Servers entfernen
      db.run(`DELETE FROM waip_clients`);
    });
  } else {
    // Datenbankdatei erstellen
    fs.openSync(dbFile, 'w');
    // leere Datenbank befuellen
    db.serialize(function() {
      // Einsatz-Tabelle erstellen
      db.run(`CREATE TABLE waip_einsaetze (
        id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
        zeitstempel DATETIME DEFAULT CURRENT_TIMESTAMP,
        einsatznummer TEXT,
        alarmzeit TEXT,
        einsatzart TEXT,
        stichwort TEXT,
        sondersignal INTEGER,
        besonderheiten TEXT,
        ort TEXT,
        ortsteil TEXT,
        strasse TEXT,
        objekt TEXT,
        objektnr TEXT,
        objektart TEXT,
        wachenfolge INTEGER,
        wgs84_x TEXT,
        wgs84_y TEXT)`);
      // Einsatzmittel-Tabelle erstellen
      // TODO: Erweitern um Status, Staerke, AGT
      db.run(`CREATE TABLE waip_einsatzmittel (
        id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
        waip_einsaetze_ID INTEGER NOT NULL,
        waip_wachen_ID INTEGER,
        wachenname TEXT,
        einsatzmittel TEXT,
        zeitstempel TEXT,
        FOREIGN KEY (waip_einsaetze_ID) REFERENCES waip_einsaetze(id) ON DELETE CASCADE ON UPDATE CASCADE)`);
      // Wachen-Tabelle erstellen
      db.run(`CREATE TABLE waip_wachen (
        id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
        nr_wache INTEGER,
        nr_traeger TEXT,
        nr_kreis INTEGER,
        name_wache TEXT,
        name_traeger TEXT,
        name_kreis TEXT)`);
      // Client-Tabelle erstellen
      db.run(`CREATE TABLE waip_clients (
        id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
        connect_time DATETIME DEFAULT CURRENT_TIMESTAMP,
        socket_id TEXT,
        client_ip TEXT,
        room_name TEXT,
        client_status TEXT)`);
      // Benutzer-Tabelle erstellen
      db.run(`CREATE TABLE waip_users (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        user TEXT,
        password TEXT,
        permissions TEXT)`);
      // Ersetzungs-Tabelle fuer Einsatzmittelnamen erstellen
      db.run(`CREATE TABLE waip_ttsreplace (
        id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
        einsatzmittel_typ TEXT,
        einsatzmittel_rufname TEXT)`);
      // Default-Wachen speichern
      db.run(`INSERT OR REPLACE INTO waip_wachen (
        nr_wache, nr_traeger, nr_kreis, name_wache, name_traeger, name_kreis)
        VALUES
        (0,\'0\',0,\'Global - Alle Einsätze\',\'Global\',\'Global\'),
        (520101,\'01\',52,\'CB FW Cottbus 1\',\'Stadt Cottbus\',\'Stadt Cottbus\'),
        (520201,\'02\',52,\'CB FW Cottbus 2\',\'Stadt Cottbus\',\'Stadt Cottbus\'),
        (521101,\'11\',52,\'CB FW Branitz\',\'Stadt Cottbus\',\'Stadt Cottbus\'),
        (521102,\'11\',52,\'CB FW Dissenchen\',\'Stadt Cottbus\',\'Stadt Cottbus\'),
        (521103,\'11\',52,\'CB FW Kahren\',\'Stadt Cottbus\',\'Stadt Cottbus\'),
        (521104,\'11\',52,\'CB FW Kiekebusch\',\'Stadt Cottbus\',\'Stadt Cottbus\'),
        (521201,\'12\',52,\'CB FW Merzdorf\',\'Stadt Cottbus\',\'Stadt Cottbus\'),
        (521202,\'12\',52,\'CB FW Sandow\',\'Stadt Cottbus\',\'Stadt Cottbus\'),
        (521203,\'12\',52,\'CB FW Saspow\',\'Stadt Cottbus\',\'Stadt Cottbus\'),
        (521204,\'12\',52,\'CB FW Willmersdorf\',\'Stadt Cottbus\',\'Stadt Cottbus\'),
        (521301,\'13\',52,\'CB FW Döbbrick\',\'Stadt Cottbus\',\'Stadt Cottbus\'),
        (521302,\'13\',52,\'CB FW Schmellwitz\',\'Stadt Cottbus\',\'Stadt Cottbus\'),
        (521303,\'13\',52,\'CB FW Sielow\',\'Stadt Cottbus\',\'Stadt Cottbus\'),
        (521304,\'13\',52,\'CB FW Ströbitz\',\'Stadt Cottbus\',\'Stadt Cottbus\'),
        (521401,\'14\',52,\'CB FW Gallinchen\',\'Stadt Cottbus\',\'Stadt Cottbus\'),
        (521402,\'14\',52,\'CB FW Groß Gaglow\',\'Stadt Cottbus\',\'Stadt Cottbus\'),
        (521403,\'14\',52,\'CB FW Madlow\',\'Stadt Cottbus\',\'Stadt Cottbus\'),
        (521404,\'14\',52,\'CB FW Sachsendorf\',\'Stadt Cottbus\',\'Stadt Cottbus\'),
        (610101,\'01\',61,\'LDS FW Lübben\',\'Stadt Lübben\',\'Landkreis Dahme-Spreewald\'),
        (610102,\'01\',61,\'LDS FW Lubolz\',\'Stadt Lübben\',\'Landkreis Dahme-Spreewald\'),
        (610104,\'01\',61,\'LDS FW Neuendorf (Lübben)\',\'Stadt Lübben\',\'Landkreis Dahme-Spreewald\'),
        (610105,\'01\',61,\'LDS FW Radensdorf\',\'Stadt Lübben\',\'Landkreis Dahme-Spreewald\'),
        (610106,\'01\',61,\'LDS FW Steinkirchen\',\'Stadt Lübben\',\'Landkreis Dahme-Spreewald\'),
        (610107,\'01\',61,\'LDS FW Treppendorf\',\'Stadt Lübben\',\'Landkreis Dahme-Spreewald\'),
        (610201,\'02\',61,\'LDS FW Bestensee\',\'Gemeinde Bestensee\',\'Landkreis Dahme-Spreewald\'),
        (610202,\'02\',61,\'LDS FW Pätz\',\'Gemeinde Bestensee\',\'Landkreis Dahme-Spreewald\'),
        (610301,\'03\',61,\'LDS FW Eichwalde\',\'Gemeinde Eichwalde\',\'Landkreis Dahme-Spreewald\'),
        (610401,\'04\',61,\'LDS FW Diepensee\',\'Stadt Königs Wusterhausen\',\'Landkreis Dahme-Spreewald\'),
        (610402,\'04\',61,\'LDS FW Königs Wusterhausen FF\',\'Stadt Königs Wusterhausen\',\'Landkreis Dahme-Spreewald\'),
        (610403,\'04\',61,\'LDS FW Königs Wusterhausen HA\',\'Stadt Königs Wusterhausen\',\'Landkreis Dahme-Spreewald\'),
        (610404,\'04\',61,\'LDS FW Kablow\',\'Stadt Königs Wusterhausen\',\'Landkreis Dahme-Spreewald\'),
        (610405,\'04\',61,\'LDS FW Niederlehme\',\'Stadt Königs Wusterhausen\',\'Landkreis Dahme-Spreewald\'),
        (610406,\'04\',61,\'LDS FW Senzig\',\'Stadt Königs Wusterhausen\',\'Landkreis Dahme-Spreewald\'),
        (610407,\'04\',61,\'LDS FW Wernsdorf\',\'Stadt Königs Wusterhausen\',\'Landkreis Dahme-Spreewald\'),
        (610408,\'04\',61,\'LDS FW Zeesen\',\'Stadt Königs Wusterhausen\',\'Landkreis Dahme-Spreewald\'),
        (610409,\'04\',61,\'LDS FW Zernsdorf\',\'Stadt Königs Wusterhausen\',\'Landkreis Dahme-Spreewald\'),
        (610501,\'05\',61,\'LDS FW Schulzendorf\',\'Gemeinde Schulzendorf\',\'Landkreis Dahme-Spreewald\'),
        (610601,\'06\',61,\'LDS FW Wildau\',\'Stadt Wildau\',\'Landkreis Dahme-Spreewald\'),
        (610702,\'07\',61,\'LDS FW Zeuthen\',\'Gemeinde Zeuthen\',\'Landkreis Dahme-Spreewald\'),
        (610703,\'07\',61,\'LDS FW Miersdorf\',\'Gemeinde Zeuthen\',\'Landkreis Dahme-Spreewald\'),
        (610802,\'08\',61,\'LDS FW Bindow\',\'Gemeinde Heidesee\',\'Landkreis Dahme-Spreewald\'),
        (610803,\'08\',61,\'LDS FW Dannenreich\',\'Gemeinde Heidesee\',\'Landkreis Dahme-Spreewald\'),
        (610804,\'08\',61,\'LDS FW Dolgenbrodt\',\'Gemeinde Heidesee\',\'Landkreis Dahme-Spreewald\'),
        (610805,\'08\',61,\'LDS FW Friedersdorf\',\'Gemeinde Heidesee\',\'Landkreis Dahme-Spreewald\'),
        (610806,\'08\',61,\'LDS FW Gräbendorf\',\'Gemeinde Heidesee\',\'Landkreis Dahme-Spreewald\'),
        (610807,\'08\',61,\'LDS FW Klein Eichholz\',\'Gemeinde Heidesee\',\'Landkreis Dahme-Spreewald\'),
        (610808,\'08\',61,\'LDS FW Kolberg\',\'Gemeinde Heidesee\',\'Landkreis Dahme-Spreewald\'),
        (610809,\'08\',61,\'LDS FW Prieros\',\'Gemeinde Heidesee\',\'Landkreis Dahme-Spreewald\'),
        (610810,\'08\',61,\'LDS FW Streganz\',\'Gemeinde Heidesee\',\'Landkreis Dahme-Spreewald\'),
        (610811,\'08\',61,\'LDS FW Wolzig\',\'Gemeinde Heidesee\',\'Landkreis Dahme-Spreewald\'),
        (610902,\'09\',61,\'LDS FW Drahnsdorf\',\'Amt Unterspreewald\',\'Landkreis Dahme-Spreewald\'),
        (610903,\'09\',61,\'LDS FW Falkenhain\',\'Amt Unterspreewald\',\'Landkreis Dahme-Spreewald\'),
        (610904,\'09\',61,\'LDS FW Krossen\',\'Amt Unterspreewald\',\'Landkreis Dahme-Spreewald\'),
        (610905,\'09\',61,\'LDS FW Schäcksdorf\',\'Amt Unterspreewald\',\'Landkreis Dahme-Spreewald\'),
        (610906,\'09\',61,\'LDS FW Golßen\',\'Amt Unterspreewald\',\'Landkreis Dahme-Spreewald\'),
        (610907,\'09\',61,\'LDS FW Altgolßen\',\'Amt Unterspreewald\',\'Landkreis Dahme-Spreewald\'),
        (610908,\'09\',61,\'LDS FW Mahlsdorf\',\'Amt Unterspreewald\',\'Landkreis Dahme-Spreewald\'),
        (610909,\'09\',61,\'LDS FW Zützen\',\'Amt Unterspreewald\',\'Landkreis Dahme-Spreewald\'),
        (610910,\'09\',61,\'LDS FW Kasel-Golzig\',\'Amt Unterspreewald\',\'Landkreis Dahme-Spreewald\'),
        (610911,\'09\',61,\'LDS FW Jetsch\',\'Amt Unterspreewald\',\'Landkreis Dahme-Spreewald\'),
        (610912,\'09\',61,\'LDS FW Schiebsdorf\',\'Amt Unterspreewald\',\'Landkreis Dahme-Spreewald\'),
        (610913,\'09\',61,\'LDS FW Glienig\',\'Amt Unterspreewald\',\'Landkreis Dahme-Spreewald\'),
        (610914,\'09\',61,\'LDS FW Sellendorf\',\'Amt Unterspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611002,\'10\',61,\'LDS FW Beesdau\',\'Gemeinde Heideblick\',\'Landkreis Dahme-Spreewald\'),
        (611003,\'10\',61,\'LDS FW Bornsdorf\',\'Gemeinde Heideblick\',\'Landkreis Dahme-Spreewald\'),
        (611004,\'10\',61,\'LDS FW Falkenberg\',\'Gemeinde Heideblick\',\'Landkreis Dahme-Spreewald\'),
        (611005,\'10\',61,\'LDS FW Gehren\',\'Gemeinde Heideblick\',\'Landkreis Dahme-Spreewald\'),
        (611006,\'10\',61,\'LDS FW Goßmar\',\'Gemeinde Heideblick\',\'Landkreis Dahme-Spreewald\'),
        (611007,\'10\',61,\'LDS FW Langengrassau\',\'Gemeinde Heideblick\',\'Landkreis Dahme-Spreewald\'),
        (611008,\'10\',61,\'LDS FW Pitschen-Pickel\',\'Gemeinde Heideblick\',\'Landkreis Dahme-Spreewald\'),
        (611009,\'10\',61,\'LDS FW Riedebeck\',\'Gemeinde Heideblick\',\'Landkreis Dahme-Spreewald\'),
        (611011,\'10\',61,\'LDS FW Walddrehna\',\'Gemeinde Heideblick\',\'Landkreis Dahme-Spreewald\'),
        (611012,\'10\',61,\'LDS FW Waltersdorf (Heideblick)\',\'Gemeinde Heideblick\',\'Landkreis Dahme-Spreewald\'),
        (611013,\'10\',61,\'LDS FW Weißack\',\'Gemeinde Heideblick\',\'Landkreis Dahme-Spreewald\'),
        (611014,\'10\',61,\'LDS FW Wüstermarke\',\'Gemeinde Heideblick\',\'Landkreis Dahme-Spreewald\'),
        (611015,\'10\',61,\'LDS FW Wehnsdorf\',\'Gemeinde Heideblick\',\'Landkreis Dahme-Spreewald\'),
        (611202,\'12\',61,\'LDS FW Luckau\',\'Stadt Luckau\',\'Landkreis Dahme-Spreewald\'),
        (611203,\'12\',61,\'LDS FW Bergen\',\'Stadt Luckau\',\'Landkreis Dahme-Spreewald\'),
        (611204,\'12\',61,\'LDS FW Cahnsdorf\',\'Stadt Luckau\',\'Landkreis Dahme-Spreewald\'),
        (611205,\'12\',61,\'LDS FW Duben\',\'Stadt Luckau\',\'Landkreis Dahme-Spreewald\'),
        (611206,\'12\',61,\'LDS FW Egsdorf (Luckau)\',\'Stadt Luckau\',\'Landkreis Dahme-Spreewald\'),
        (611207,\'12\',61,\'LDS FW Fürstlich Drehna\',\'Stadt Luckau\',\'Landkreis Dahme-Spreewald\'),
        (611208,\'12\',61,\'LDS FW Gießmannsdorf\',\'Stadt Luckau\',\'Landkreis Dahme-Spreewald\'),
        (611209,\'12\',61,\'LDS FW Görlsdorf\',\'Stadt Luckau\',\'Landkreis Dahme-Spreewald\'),
        (611210,\'12\',61,\'LDS FW Karche Zaacko\',\'Stadt Luckau\',\'Landkreis Dahme-Spreewald\'),
        (611211,\'12\',61,\'LDS FW Kreblitz\',\'Stadt Luckau\',\'Landkreis Dahme-Spreewald\'),
        (611212,\'12\',61,\'LDS FW Kümmritz\',\'Stadt Luckau\',\'Landkreis Dahme-Spreewald\'),
        (611213,\'12\',61,\'LDS FW Paserin\',\'Stadt Luckau\',\'Landkreis Dahme-Spreewald\'),
        (611214,\'12\',61,\'LDS FW Rüdingsdorf\',\'Stadt Luckau\',\'Landkreis Dahme-Spreewald\'),
        (611215,\'12\',61,\'LDS FW Schlabendorf\',\'Stadt Luckau\',\'Landkreis Dahme-Spreewald\'),
        (611216,\'12\',61,\'LDS FW Terpt\',\'Stadt Luckau\',\'Landkreis Dahme-Spreewald\'),
        (611217,\'12\',61,\'LDS FW Uckro\',\'Stadt Luckau\',\'Landkreis Dahme-Spreewald\'),
        (611218,\'12\',61,\'LDS FW Willmersdorf-Stöbritz\',\'Stadt Luckau\',\'Landkreis Dahme-Spreewald\'),
        (611219,\'12\',61,\'LDS FW Zieckau\',\'Stadt Luckau\',\'Landkreis Dahme-Spreewald\'),
        (611220,\'12\',61,\'LDS FW Zöllmersdorf\',\'Stadt Luckau\',\'Landkreis Dahme-Spreewald\'),
        (611221,\'12\',61,\'LDS FW Alteno\',\'Stadt Luckau\',\'Landkreis Dahme-Spreewald\'),
        (611222,\'12\',61,\'LDS FW Freiimfelde\',\'Stadt Luckau\',\'Landkreis Dahme-Spreewald\'),
        (611223,\'12\',61,\'LDS FW Kaden\',\'Stadt Luckau\',\'Landkreis Dahme-Spreewald\'),
        (611224,\'12\',61,\'LDS FW Pelkwitz\',\'Stadt Luckau\',\'Landkreis Dahme-Spreewald\'),
        (611225,\'12\',61,\'LDS FW Schollen\',\'Stadt Luckau\',\'Landkreis Dahme-Spreewald\'),
        (611302,\'13\',61,\'LDS FW Alt Schadow\',\'Gemeinde Märkische Heide\',\'Landkreis Dahme-Spreewald\'),
        (611303,\'13\',61,\'LDS FW Biebersdorf\',\'Gemeinde Märkische Heide\',\'Landkreis Dahme-Spreewald\'),
        (611304,\'13\',61,\'LDS FW Dollgen\',\'Gemeinde Märkische Heide\',\'Landkreis Dahme-Spreewald\'),
        (611305,\'13\',61,\'LDS FW Dürrenhofe\',\'Gemeinde Märkische Heide\',\'Landkreis Dahme-Spreewald\'),
        (611306,\'13\',61,\'LDS FW Glietz\',\'Gemeinde Märkische Heide\',\'Landkreis Dahme-Spreewald\'),
        (611307,\'13\',61,\'LDS FW Gröditsch\',\'Gemeinde Märkische Heide\',\'Landkreis Dahme-Spreewald\'),
        (611308,\'13\',61,\'LDS FW Groß Leine\',\'Gemeinde Märkische Heide\',\'Landkreis Dahme-Spreewald\'),
        (611309,\'13\',61,\'LDS FW Groß Leuthen\',\'Gemeinde Märkische Heide\',\'Landkreis Dahme-Spreewald\'),
        (611310,\'13\',61,\'LDS FW Hohenbrück\',\'Gemeinde Märkische Heide\',\'Landkreis Dahme-Spreewald\'),
        (611311,\'13\',61,\'LDS FW Klein Leine\',\'Gemeinde Märkische Heide\',\'Landkreis Dahme-Spreewald\'),
        (611312,\'13\',61,\'LDS FW Krugau\',\'Gemeinde Märkische Heide\',\'Landkreis Dahme-Spreewald\'),
        (611313,\'13\',61,\'LDS FW Kuschkow\',\'Gemeinde Märkische Heide\',\'Landkreis Dahme-Spreewald\'),
        (611314,\'13\',61,\'LDS FW Leibchel\',\'Gemeinde Märkische Heide\',\'Landkreis Dahme-Spreewald\'),
        (611315,\'13\',61,\'LDS FW Neu Schadow\',\'Gemeinde Märkische Heide\',\'Landkreis Dahme-Spreewald\'),
        (611316,\'13\',61,\'LDS FW Plattkow\',\'Gemeinde Märkische Heide\',\'Landkreis Dahme-Spreewald\'),
        (611317,\'13\',61,\'LDS FW Pretschen\',\'Gemeinde Märkische Heide\',\'Landkreis Dahme-Spreewald\'),
        (611318,\'13\',61,\'LDS FW Schuhlen-Wiese\',\'Gemeinde Märkische Heide\',\'Landkreis Dahme-Spreewald\'),
        (611319,\'13\',61,\'LDS FW Bückchen\',\'Gemeinde Märkische Heide\',\'Landkreis Dahme-Spreewald\'),
        (611320,\'13\',61,\'LDS FW Wittmannsdorf\',\'Gemeinde Märkische Heide\',\'Landkreis Dahme-Spreewald\'),
        (611402,\'14\',61,\'LDS FW Mittenwalde\',\'Stadt Mittenwalde\',\'Landkreis Dahme-Spreewald\'),
        (611403,\'14\',61,\'LDS FW Brusendorf\',\'Stadt Mittenwalde\',\'Landkreis Dahme-Spreewald\'),
        (611404,\'14\',61,\'LDS FW Gallun\',\'Stadt Mittenwalde\',\'Landkreis Dahme-Spreewald\'),
        (611405,\'14\',61,\'LDS FW Krummensee\',\'Stadt Mittenwalde\',\'Landkreis Dahme-Spreewald\'),
        (611406,\'14\',61,\'LDS FW Motzen\',\'Stadt Mittenwalde\',\'Landkreis Dahme-Spreewald\'),
        (611407,\'14\',61,\'LDS FW Ragow\',\'Stadt Mittenwalde\',\'Landkreis Dahme-Spreewald\'),
        (611408,\'14\',61,\'LDS FW Schenkendorf\',\'Stadt Mittenwalde\',\'Landkreis Dahme-Spreewald\'),
        (611409,\'14\',61,\'LDS FW Telz\',\'Stadt Mittenwalde\',\'Landkreis Dahme-Spreewald\'),
        (611410,\'14\',61,\'LDS FW Töpchin\',\'Stadt Mittenwalde\',\'Landkreis Dahme-Spreewald\'),
        (611502,\'15\',61,\'LDS FW Alt Zauche\',\'Amt Lieberose/Oberspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611503,\'15\',61,\'LDS FW Wußwerk\',\'Amt Lieberose/Oberspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611504,\'15\',61,\'LDS FW Byhleguhre\',\'Amt Lieberose/Oberspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611505,\'15\',61,\'LDS FW Byhlen\',\'Amt Lieberose/Oberspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611506,\'15\',61,\'LDS FW Jamlitz\',\'Amt Lieberose/Oberspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611507,\'15\',61,\'LDS FW Leeskow\',\'Amt Lieberose/Oberspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611508,\'15\',61,\'LDS FW Ullersdorf\',\'Amt Lieberose/Oberspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611509,\'15\',61,\'LDS FW Lieberose\',\'Amt Lieberose/Oberspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611510,\'15\',61,\'LDS FW Blasdorf\',\'Amt Lieberose/Oberspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611511,\'15\',61,\'LDS FW Doberburg\',\'Amt Lieberose/Oberspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611512,\'15\',61,\'LDS FW Goschen\',\'Amt Lieberose/Oberspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611513,\'15\',61,\'LDS FW Trebitz\',\'Amt Lieberose/Oberspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611514,\'15\',61,\'LDS FW Neu Zauche\',\'Amt Lieberose/Oberspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611515,\'15\',61,\'LDS FW Briesensee\',\'Amt Lieberose/Oberspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611516,\'15\',61,\'LDS FW Caminchen\',\'Amt Lieberose/Oberspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611517,\'15\',61,\'LDS FW Ressen\',\'Amt Lieberose/Oberspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611518,\'15\',61,\'LDS FW Jessern\',\'Amt Lieberose/Oberspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611519,\'15\',61,\'LDS FW Lamsfeld-Groß Liebitz\',\'Amt Lieberose/Oberspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611520,\'15\',61,\'LDS FW Mochow\',\'Amt Lieberose/Oberspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611521,\'15\',61,\'LDS FW Speichrow\',\'Amt Lieberose/Oberspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611522,\'15\',61,\'LDS FW Goyatz\',\'Amt Lieberose/Oberspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611523,\'15\',61,\'LDS FW Guhlen\',\'Amt Lieberose/Oberspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611524,\'15\',61,\'LDS FW Siegadel\',\'Amt Lieberose/Oberspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611525,\'15\',61,\'LDS FW Zaue\',\'Amt Lieberose/Oberspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611526,\'15\',61,\'LDS FW Butzen\',\'Amt Lieberose/Oberspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611527,\'15\',61,\'LDS FW Laasow\',\'Amt Lieberose/Oberspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611528,\'15\',61,\'LDS FW Sacrow\',\'Amt Lieberose/Oberspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611529,\'15\',61,\'LDS FW Waldow\',\'Amt Lieberose/Oberspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611530,\'15\',61,\'LDS FW Straupitz\',\'Amt Lieberose/Oberspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611602,\'16\',61,\'LDS FW Groß Köris\',\'Amt Schenkenländchen\',\'Landkreis Dahme-Spreewald\'),
        (611603,\'16\',61,\'LDS FW Halbe\',\'Amt Schenkenländchen\',\'Landkreis Dahme-Spreewald\'),
        (611604,\'16\',61,\'LDS FW Briesen\',\'Amt Schenkenländchen\',\'Landkreis Dahme-Spreewald\'),
        (611605,\'16\',61,\'LDS FW Freidorf\',\'Amt Schenkenländchen\',\'Landkreis Dahme-Spreewald\'),
        (611606,\'16\',61,\'LDS FW Teurow\',\'Amt Schenkenländchen\',\'Landkreis Dahme-Spreewald\'),
        (611607,\'16\',61,\'LDS FW Märkisch Buchholz\',\'Amt Schenkenländchen\',\'Landkreis Dahme-Spreewald\'),
        (611608,\'16\',61,\'LDS FW Münchehofe\',\'Amt Schenkenländchen\',\'Landkreis Dahme-Spreewald\'),
        (611609,\'16\',61,\'LDS FW Birkholz\',\'Amt Schenkenländchen\',\'Landkreis Dahme-Spreewald\'),
        (611610,\'16\',61,\'LDS FW Hermsdorf\',\'Amt Schenkenländchen\',\'Landkreis Dahme-Spreewald\'),
        (611611,\'16\',61,\'LDS FW Schwerin\',\'Amt Schenkenländchen\',\'Landkreis Dahme-Spreewald\'),
        (611612,\'16\',61,\'LDS FW Teupitz\',\'Amt Schenkenländchen\',\'Landkreis Dahme-Spreewald\'),
        (611613,\'16\',61,\'LDS FW Egsdorf (Teupitz)\',\'Amt Schenkenländchen\',\'Landkreis Dahme-Spreewald\'),
        (611614,\'16\',61,\'LDS FW Neuendorf (Teupitz)\',\'Amt Schenkenländchen\',\'Landkreis Dahme-Spreewald\'),
        (611615,\'16\',61,\'LDS FW Tornow\',\'Amt Schenkenländchen\',\'Landkreis Dahme-Spreewald\'),
        (611616,\'16\',61,\'LDS FW Oderin\',\'Amt Schenkenländchen\',\'Landkreis Dahme-Spreewald\'),
        (611702,\'17\',61,\'LDS FW Schönefeld\',\'Gemeinde Schönefeld\',\'Landkreis Dahme-Spreewald\'),
        (611703,\'17\',61,\'LDS FW Großziethen\',\'Gemeinde Schönefeld\',\'Landkreis Dahme-Spreewald\'),
        (611704,\'17\',61,\'LDS FW Kiekebusch\',\'Gemeinde Schönefeld\',\'Landkreis Dahme-Spreewald\'),
        (611705,\'17\',61,\'LDS FW Rotberg\',\'Gemeinde Schönefeld\',\'Landkreis Dahme-Spreewald\'),
        (611706,\'17\',61,\'LDS FW Selchow\',\'Gemeinde Schönefeld\',\'Landkreis Dahme-Spreewald\'),
        (611707,\'17\',61,\'LDS FW Waltersdorf\',\'Gemeinde Schönefeld\',\'Landkreis Dahme-Spreewald\'),
        (611708,\'17\',61,\'LDS FW Waßmannsdorf\',\'Gemeinde Schönefeld\',\'Landkreis Dahme-Spreewald\'),
        (611902,\'19\',61,\'LDS FW Freiwalde\',\'Amt Unterspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611903,\'19\',61,\'LDS FW Niewitz\',\'Amt Unterspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611904,\'19\',61,\'LDS FW Reichwalde\',\'Amt Unterspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611906,\'19\',61,\'LDS FW Groß Wasserburg\',\'Amt Unterspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611908,\'19\',61,\'LDS FW Rietzneuendorf\',\'Amt Unterspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611909,\'19\',61,\'LDS FW Staakow\',\'Amt Unterspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611910,\'19\',61,\'LDS FW Schlepzig\',\'Amt Unterspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611911,\'19\',61,\'LDS FW Schönwalde\',\'Amt Unterspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611912,\'19\',61,\'LDS FW Waldow/Brand\',\'Amt Unterspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611913,\'19\',61,\'LDS FW Leibsch\',\'Amt Unterspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611914,\'19\',61,\'LDS FW Neu Lübbenau\',\'Amt Unterspreewald\',\'Landkreis Dahme-Spreewald\'),
        (611915,\'19\',61,\'LDS FW Neuendorf am See\',\'Amt Unterspreewald\',\'Landkreis Dahme-Spreewald\'),
        (619001,\'90\',61,\'LDS RW Lübben\',\'Rettungswachen Dahme-Spreewald\',\'Landkreis Dahme-Spreewald\'),
        (619002,\'90\',61,\'LDS RW Bestensee\',\'Rettungswachen Dahme-Spreewald\',\'Landkreis Dahme-Spreewald\'),
        (619004,\'90\',61,\'LDS RW Königs Wusterhausen\',\'Rettungswachen Dahme-Spreewald\',\'Landkreis Dahme-Spreewald\'),
        (619005,\'90\',61,\'LDS RW Schulzendorf\',\'Rettungswachen Dahme-Spreewald\',\'Landkreis Dahme-Spreewald\'),
        (619009,\'90\',61,\'LDS RW Golßen\',\'Rettungswachen Dahme-Spreewald\',\'Landkreis Dahme-Spreewald\'),
        (619012,\'90\',61,\'LDS RW Luckau\',\'Rettungswachen Dahme-Spreewald\',\'Landkreis Dahme-Spreewald\'),
        (619015,\'90\',61,\'LDS RW Goyatz\',\'Rettungswachen Dahme-Spreewald\',\'Landkreis Dahme-Spreewald\'),
        (619016,\'90\',61,\'LDS RW Teupitz\',\'Rettungswachen Dahme-Spreewald\',\'Landkreis Dahme-Spreewald\'),
        (619017,\'90\',61,\'LDS RW Schönefeld\',\'Rettungswachen Dahme-Spreewald\',\'Landkreis Dahme-Spreewald\'),
        (619019,\'90\',61,\'LDS RW Leibsch\',\'Rettungswachen Dahme-Spreewald\',\'Landkreis Dahme-Spreewald\'),
        (620102,\'01\',62,\'EE FW Bad Liebenwerda\',\'Stadt Bad Liebenwerda\',\'Landkreis Elbe-Elster\'),
        (620103,\'01\',62,\'EE FW Dobra\',\'Stadt Bad Liebenwerda\',\'Landkreis Elbe-Elster\'),
        (620104,\'01\',62,\'EE FW Kosilenzien\',\'Stadt Bad Liebenwerda\',\'Landkreis Elbe-Elster\'),
        (620105,\'01\',62,\'EE FW Kröbeln\',\'Stadt Bad Liebenwerda\',\'Landkreis Elbe-Elster\'),
        (620106,\'01\',62,\'EE FW Langenrieth\',\'Stadt Bad Liebenwerda\',\'Landkreis Elbe-Elster\'),
        (620107,\'01\',62,\'EE FW Lausitz\',\'Stadt Bad Liebenwerda\',\'Landkreis Elbe-Elster\'),
        (620108,\'01\',62,\'EE FW Maasdorf \',\'Stadt Bad Liebenwerda\',\'Landkreis Elbe-Elster\'),
        (620109,\'01\',62,\'EE FW Möglenz\',\'Stadt Bad Liebenwerda\',\'Landkreis Elbe-Elster\'),
        (620110,\'01\',62,\'EE FW Neuburxdorf\',\'Stadt Bad Liebenwerda\',\'Landkreis Elbe-Elster\'),
        (620111,\'01\',62,\'EE FW Oschätzchen\',\'Stadt Bad Liebenwerda\',\'Landkreis Elbe-Elster\'),
        (620112,\'01\',62,\'EE FW Prieschka\',\'Stadt Bad Liebenwerda\',\'Landkreis Elbe-Elster\'),
        (620113,\'01\',62,\'EE FW Thalberg\',\'Stadt Bad Liebenwerda\',\'Landkreis Elbe-Elster\'),
        (620114,\'01\',62,\'EE FW Theisa\',\'Stadt Bad Liebenwerda\',\'Landkreis Elbe-Elster\'),
        (620115,\'01\',62,\'EE FW Zeischa\',\'Stadt Bad Liebenwerda\',\'Landkreis Elbe-Elster\'),
        (620202,\'02\',62,\'EE FW Elsterwerda\',\'Stadt Elsterwerda\',\'Landkreis Elbe-Elster\'),
        (620203,\'02\',62,\'EE FW Elsterwerda Biehla\',\'Stadt Elsterwerda\',\'Landkreis Elbe-Elster\'),
        (620204,\'02\',62,\'EE FW Kraupa\',\'Stadt Elsterwerda\',\'Landkreis Elbe-Elster\'),
        (620302,\'03\',62,\'EE FW Finsterwalde\',\'Stadt Finsterwalde\',\'Landkreis Elbe-Elster\'),
        (620303,\'03\',62,\'EE FW Pechhütte\',\'Stadt Finsterwalde\',\'Landkreis Elbe-Elster\'),
        (620304,\'03\',62,\'EE FW Sorno\',\'Stadt Finsterwalde\',\'Landkreis Elbe-Elster\'),
        (620305,\'03\',62,\'EE FW Finsterwalde Süd\',\'Stadt Finsterwalde\',\'Landkreis Elbe-Elster\'),
        (620402,\'04\',62,\'EE FW Doberlug\',\'Stadt Doberlug-Kirchhain\',\'Landkreis Elbe-Elster\'),
        (620403,\'04\',62,\'EE FW Arenzhain\',\'Stadt Doberlug-Kirchhain\',\'Landkreis Elbe-Elster\'),
        (620404,\'04\',62,\'EE FW Buchhain\',\'Stadt Doberlug-Kirchhain\',\'Landkreis Elbe-Elster\'),
        (620405,\'04\',62,\'EE FW Dübrichen\',\'Stadt Doberlug-Kirchhain\',\'Landkreis Elbe-Elster\'),
        (620406,\'04\',62,\'EE FW Frankena\',\'Stadt Doberlug-Kirchhain\',\'Landkreis Elbe-Elster\'),
        (620407,\'04\',62,\'EE FW Hennersdorf\',\'Stadt Doberlug-Kirchhain\',\'Landkreis Elbe-Elster\'),
        (620408,\'04\',62,\'EE FW Kirchhain\',\'Stadt Doberlug-Kirchhain\',\'Landkreis Elbe-Elster\'),
        (620409,\'04\',62,\'EE FW Lichtena\',\'Stadt Doberlug-Kirchhain\',\'Landkreis Elbe-Elster\'),
        (620410,\'04\',62,\'EE FW Lugau\',\'Stadt Doberlug-Kirchhain\',\'Landkreis Elbe-Elster\'),
        (620411,\'04\',62,\'EE FW Nexdorf\',\'Stadt Doberlug-Kirchhain\',\'Landkreis Elbe-Elster\'),
        (620412,\'04\',62,\'EE FW Prießen\',\'Stadt Doberlug-Kirchhain\',\'Landkreis Elbe-Elster\'),
        (620413,\'04\',62,\'EE FW Trebbus\',\'Stadt Doberlug-Kirchhain\',\'Landkreis Elbe-Elster\'),
        (620414,\'04\',62,\'EE FW Werenzhain\',\'Stadt Doberlug-Kirchhain\',\'Landkreis Elbe-Elster\'),
        (620502,\'05\',62,\'EE FW Drößig\',\'Amt Elsterland\',\'Landkreis Elbe-Elster\'),
        (620503,\'05\',62,\'EE FW Eichholz\',\'Amt Elsterland\',\'Landkreis Elbe-Elster\'),
        (620504,\'05\',62,\'EE FW Fischwasser\',\'Amt Elsterland\',\'Landkreis Elbe-Elster\'),
        (620505,\'05\',62,\'EE FW Rückersdorf\',\'Amt Elsterland\',\'Landkreis Elbe-Elster\'),
        (620506,\'05\',62,\'EE FW Friedersdorf (Oppelh.)\',\'Amt Elsterland\',\'Landkreis Elbe-Elster\'),
        (620507,\'05\',62,\'EE FW Oppelhain\',\'Amt Elsterland\',\'Landkreis Elbe-Elster\'),
        (620508,\'05\',62,\'EE FW Schilda\',\'Amt Elsterland\',\'Landkreis Elbe-Elster\'),
        (620509,\'05\',62,\'EE FW Schönborn\',\'Amt Elsterland\',\'Landkreis Elbe-Elster\'),
        (620510,\'05\',62,\'EE FW Gruhno\',\'Amt Elsterland\',\'Landkreis Elbe-Elster\'),
        (620511,\'05\',62,\'EE FW Lindena\',\'Amt Elsterland\',\'Landkreis Elbe-Elster\'),
        (620512,\'05\',62,\'EE FW Schadewitz\',\'Amt Elsterland\',\'Landkreis Elbe-Elster\'),
        (620513,\'05\',62,\'EE FW Tröbitz\',\'Amt Elsterland\',\'Landkreis Elbe-Elster\'),
        (620602,\'06\',62,\'EE FW Falkenberg\',\'Stadt Falkenberg/Elster\',\'Landkreis Elbe-Elster\'),
        (620603,\'06\',62,\'EE FW Beyern\',\'Stadt Falkenberg/Elster\',\'Landkreis Elbe-Elster\'),
        (620604,\'06\',62,\'EE FW Großrössen\',\'Stadt Falkenberg/Elster\',\'Landkreis Elbe-Elster\'),
        (620605,\'06\',62,\'EE FW Kölsa\',\'Stadt Falkenberg/Elster\',\'Landkreis Elbe-Elster\'),
        (620606,\'06\',62,\'EE FW Rehfeld\',\'Stadt Falkenberg/Elster\',\'Landkreis Elbe-Elster\'),
        (620607,\'06\',62,\'EE FW Schmerkendorf\',\'Stadt Falkenberg/Elster\',\'Landkreis Elbe-Elster\'),
        (620702,\'07\',62,\'EE FW Herzberg\',\'Stadt Herzberg\',\'Landkreis Elbe-Elster\'),
        (620703,\'07\',62,\'EE FW Arnsnesta\',\'Stadt Herzberg\',\'Landkreis Elbe-Elster\'),
        (620704,\'07\',62,\'EE FW Borken\',\'Stadt Herzberg\',\'Landkreis Elbe-Elster\'),
        (620705,\'07\',62,\'EE FW Buckau Hz\',\'Stadt Herzberg\',\'Landkreis Elbe-Elster\'),
        (620706,\'07\',62,\'EE FW Fermerswalde\',\'Stadt Herzberg\',\'Landkreis Elbe-Elster\'),
        (620707,\'07\',62,\'EE FW Frauenhorst\',\'Stadt Herzberg\',\'Landkreis Elbe-Elster\'),
        (620708,\'07\',62,\'EE FW Friedersdorf Hz\',\'Stadt Herzberg\',\'Landkreis Elbe-Elster\'),
        (620709,\'07\',62,\'EE FW Friedrichsluga\',\'Stadt Herzberg\',\'Landkreis Elbe-Elster\'),
        (620710,\'07\',62,\'EE FW Gräfendorf\',\'Stadt Herzberg\',\'Landkreis Elbe-Elster\'),
        (620711,\'07\',62,\'EE FW Löhsten\',\'Stadt Herzberg\',\'Landkreis Elbe-Elster\'),
        (620712,\'07\',62,\'EE FW Mahdel\',\'Stadt Herzberg\',\'Landkreis Elbe-Elster\'),
        (620713,\'07\',62,\'EE FW Osteroda\',\'Stadt Herzberg\',\'Landkreis Elbe-Elster\'),
        (620714,\'07\',62,\'EE FW Rahnisdorf\',\'Stadt Herzberg\',\'Landkreis Elbe-Elster\'),
        (620715,\'07\',62,\'EE FW Züllsdorf\',\'Stadt Herzberg\',\'Landkreis Elbe-Elster\'),
        (620802,\'08\',62,\'EE FW Crinitz\',\'Amt Kleine Elster\',\'Landkreis Elbe-Elster\'),
        (620803,\'08\',62,\'EE FW Gahro\',\'Amt Kleine Elster\',\'Landkreis Elbe-Elster\'),
        (620804,\'08\',62,\'EE FW Lichterfeld\',\'Amt Kleine Elster\',\'Landkreis Elbe-Elster\'),
        (620805,\'08\',62,\'EE FW Lieskau\',\'Amt Kleine Elster\',\'Landkreis Elbe-Elster\'),
        (620806,\'08\',62,\'EE FW Schacksdorf\',\'Amt Kleine Elster\',\'Landkreis Elbe-Elster\'),
        (620807,\'08\',62,\'EE FW Babben\',\'Amt Kleine Elster\',\'Landkreis Elbe-Elster\'),
        (620808,\'08\',62,\'EE FW Betten\',\'Amt Kleine Elster\',\'Landkreis Elbe-Elster\'),
        (620809,\'08\',62,\'EE FW Gröbitz\',\'Amt Kleine Elster\',\'Landkreis Elbe-Elster\'),
        (620810,\'08\',62,\'EE FW Lindthal\',\'Amt Kleine Elster\',\'Landkreis Elbe-Elster\'),
        (620811,\'08\',62,\'EE FW Massen\',\'Amt Kleine Elster\',\'Landkreis Elbe-Elster\'),
        (620812,\'08\',62,\'EE FW Ponnsdorf\',\'Amt Kleine Elster\',\'Landkreis Elbe-Elster\'),
        (620813,\'08\',62,\'EE FW Tanneberg\',\'Amt Kleine Elster\',\'Landkreis Elbe-Elster\'),
        (620814,\'08\',62,\'EE FW Sallgast\',\'Amt Kleine Elster\',\'Landkreis Elbe-Elster\'),
        (620815,\'08\',62,\'EE FW Dollenchen\',\'Amt Kleine Elster\',\'Landkreis Elbe-Elster\'),
        (620816,\'08\',62,\'EE FW Göllnitz\',\'Amt Kleine Elster\',\'Landkreis Elbe-Elster\'),
        (620817,\'08\',62,\'EE FW Zürchel\',\'Amt Kleine Elster\',\'Landkreis Elbe-Elster\'),
        (620902,\'09\',62,\'EE FW Mühlberg\',\'Amt Plessa\',\'Landkreis Elbe-Elster\'),
        (620903,\'09\',62,\'EE FW Altenau\',\'Stadt Mühlberg/Elbe\',\'Landkreis Elbe-Elster\'),
        (620904,\'09\',62,\'EE FW Brottewitz\',\'Stadt Mühlberg/Elbe\',\'Landkreis Elbe-Elster\'),
        (620905,\'09\',62,\'EE FW Fichtenberg\',\'Stadt Mühlberg/Elbe\',\'Landkreis Elbe-Elster\'),
        (620906,\'09\',62,\'EE FW Koßdorf\',\'Stadt Mühlberg/Elbe\',\'Landkreis Elbe-Elster\'),
        (620907,\'09\',62,\'EE FW Martinskirchen\',\'Stadt Mühlberg/Elbe\',\'Landkreis Elbe-Elster\'),
        (621002,\'10\',62,\'EE FW Gorden\',\'Amt Plessa\',\'Landkreis Elbe-Elster\'),
        (621003,\'10\',62,\'EE FW Staupitz\',\'Amt Plessa\',\'Landkreis Elbe-Elster\'),
        (621004,\'10\',62,\'EE FW Hohenleipisch\',\'Amt Plessa\',\'Landkreis Elbe-Elster\'),
        (621005,\'10\',62,\'EE FW Dreska\',\'Amt Plessa\',\'Landkreis Elbe-Elster\'),
        (621006,\'10\',62,\'EE FW Plessa\',\'Amt Plessa\',\'Landkreis Elbe-Elster\'),
        (621007,\'10\',62,\'EE FW Döllingen\',\'Amt Plessa\',\'Landkreis Elbe-Elster\'),
        (621008,\'10\',62,\'EE FW Kahla\',\'Amt Plessa\',\'Landkreis Elbe-Elster\'),
        (621009,\'10\',62,\'EE FW Plessa-Süd\',\'Amt Plessa\',\'Landkreis Elbe-Elster\'),
        (621010,\'10\',62,\'EE FW Schraden\',\'Amt Plessa\',\'Landkreis Elbe-Elster\'),
        (621102,\'11\',62,\'EE FW Haida\',\'Gemeinde Röderland\',\'Landkreis Elbe-Elster\'),
        (621103,\'11\',62,\'EE FW Prösen\',\'Gemeinde Röderland\',\'Landkreis Elbe-Elster\'),
        (621104,\'11\',62,\'EE FW Reichenhain\',\'Gemeinde Röderland\',\'Landkreis Elbe-Elster\'),
        (621105,\'11\',62,\'EE FW Saathain\',\'Gemeinde Röderland\',\'Landkreis Elbe-Elster\'),
        (621106,\'11\',62,\'EE FW Stolzenhain an der Röder\',\'Gemeinde Röderland\',\'Landkreis Elbe-Elster\'),
        (621107,\'11\',62,\'EE FW Wainsdorf\',\'Gemeinde Röderland\',\'Landkreis Elbe-Elster\'),
        (621108,\'11\',62,\'EE FW Würdenhain\',\'Gemeinde Röderland\',\'Landkreis Elbe-Elster\'),
        (621202,\'12\',62,\'EE FW Hillmersdorf\',\'Amt Schlieben\',\'Landkreis Elbe-Elster\'),
        (621203,\'12\',62,\'EE FW Naundorf\',\'Amt Schlieben\',\'Landkreis Elbe-Elster\'),
        (621204,\'12\',62,\'EE FW Stechau\',\'Amt Schlieben\',\'Landkreis Elbe-Elster\'),
        (621205,\'12\',62,\'EE FW Hohenbucko\',\'Amt Schlieben\',\'Landkreis Elbe-Elster\'),
        (621206,\'12\',62,\'EE FW Proßmarke\',\'Amt Schlieben\',\'Landkreis Elbe-Elster\'),
        (621207,\'12\',62,\'EE FW Kolochau\',\'Amt Schlieben\',\'Landkreis Elbe-Elster\'),
        (621208,\'12\',62,\'EE FW Malitschkendorf\',\'Amt Schlieben\',\'Landkreis Elbe-Elster\'),
        (621209,\'12\',62,\'EE FW Polzen\',\'Amt Schlieben\',\'Landkreis Elbe-Elster\'),
        (621210,\'12\',62,\'EE FW Lebusa\',\'Amt Schlieben\',\'Landkreis Elbe-Elster\'),
        (621211,\'12\',62,\'EE FW Freileben\',\'Amt Schlieben\',\'Landkreis Elbe-Elster\'),
        (621212,\'12\',62,\'EE FW Körba\',\'Amt Schlieben\',\'Landkreis Elbe-Elster\'),
        (621213,\'12\',62,\'EE FW Schlieben\',\'Amt Schlieben\',\'Landkreis Elbe-Elster\'),
        (621214,\'12\',62,\'EE FW Frankenhain\',\'Amt Schlieben\',\'Landkreis Elbe-Elster\'),
        (621215,\'12\',62,\'EE FW Jagsal\',\'Amt Schlieben\',\'Landkreis Elbe-Elster\'),
        (621216,\'12\',62,\'EE FW Krassig\',\'Amt Schlieben\',\'Landkreis Elbe-Elster\'),
        (621217,\'12\',62,\'EE FW Oelsig\',\'Amt Schlieben\',\'Landkreis Elbe-Elster\'),
        (621218,\'12\',62,\'EE FW Wehrhain\',\'Amt Schlieben\',\'Landkreis Elbe-Elster\'),
        (621219,\'12\',62,\'EE FW Werchau\',\'Amt Schlieben\',\'Landkreis Elbe-Elster\'),
        (621302,\'13\',62,\'EE FW Schönewalde\',\'Stadt Schönewalde\',\'Landkreis Elbe-Elster\'),
        (621303,\'13\',62,\'EE FW Ahlsdorf\',\'Stadt Schönewalde\',\'Landkreis Elbe-Elster\'),
        (621304,\'13\',62,\'EE FW Bernsdorf\',\'Stadt Schönewalde\',\'Landkreis Elbe-Elster\'),
        (621305,\'13\',62,\'EE FW Brandis\',\'Stadt Schönewalde\',\'Landkreis Elbe-Elster\'),
        (621306,\'13\',62,\'EE FW Dubro\',\'Stadt Schönewalde\',\'Landkreis Elbe-Elster\'),
        (621307,\'13\',62,\'EE FW Grassau\',\'Stadt Schönewalde\',\'Landkreis Elbe-Elster\'),
        (621308,\'13\',62,\'EE FW Hartmannsdorf\',\'Stadt Schönewalde\',\'Landkreis Elbe-Elster\'),
        (621309,\'13\',62,\'EE FW Hohenkuhnsdorf\',\'Stadt Schönewalde\',\'Landkreis Elbe-Elster\'),
        (621310,\'13\',62,\'EE FW Jeßnigk\',\'Stadt Schönewalde\',\'Landkreis Elbe-Elster\'),
        (621311,\'13\',62,\'EE FW Knippelsdorf\',\'Stadt Schönewalde\',\'Landkreis Elbe-Elster\'),
        (621312,\'13\',62,\'EE FW Stolzenhain\',\'Stadt Schönewalde\',\'Landkreis Elbe-Elster\'),
        (621313,\'13\',62,\'EE FW Wiepersdorf\',\'Stadt Schönewalde\',\'Landkreis Elbe-Elster\'),
        (621314,\'13\',62,\'EE FW Wildenau\',\'Stadt Schönewalde\',\'Landkreis Elbe-Elster\'),
        (621402,\'14\',62,\'EE FW Gröden\',\'Amt Schradenland\',\'Landkreis Elbe-Elster\'),
        (621403,\'14\',62,\'EE FW Großthiemig\',\'Amt Schradenland\',\'Landkreis Elbe-Elster\'),
        (621404,\'14\',62,\'EE FW Hirschfeld\',\'Amt Schradenland\',\'Landkreis Elbe-Elster\'),
        (621405,\'14\',62,\'EE FW Merzdorf\',\'Amt Schradenland\',\'Landkreis Elbe-Elster\'),
        (621502,\'15\',62,\'EE FW Sonnewalde\',\'Stadt Sonnewalde\',\'Landkreis Elbe-Elster\'),
        (621503,\'15\',62,\'EE FW Birkwalde\',\'Stadt Sonnewalde\',\'Landkreis Elbe-Elster\'),
        (621504,\'15\',62,\'EE FW Breitenau\',\'Stadt Sonnewalde\',\'Landkreis Elbe-Elster\'),
        (621505,\'15\',62,\'EE FW Brenitz\',\'Stadt Sonnewalde\',\'Landkreis Elbe-Elster\'),
        (621506,\'15\',62,\'EE FW Dabern\',\'Stadt Sonnewalde\',\'Landkreis Elbe-Elster\'),
        (621507,\'15\',62,\'EE FW Friedersdorf Sowa\',\'Stadt Sonnewalde\',\'Landkreis Elbe-Elster\'),
        (621508,\'15\',62,\'EE FW Goßmar\',\'Stadt Sonnewalde\',\'Landkreis Elbe-Elster\'),
        (621509,\'15\',62,\'EE FW Großbahren\',\'Stadt Sonnewalde\',\'Landkreis Elbe-Elster\'),
        (621510,\'15\',62,\'EE FW Großkrausnik\',\'Stadt Sonnewalde\',\'Landkreis Elbe-Elster\'),
        (621511,\'15\',62,\'EE FW Kleinbahren\',\'Stadt Sonnewalde\',\'Landkreis Elbe-Elster\'),
        (621512,\'15\',62,\'EE FW Kleinkrausnik\',\'Stadt Sonnewalde\',\'Landkreis Elbe-Elster\'),
        (621513,\'15\',62,\'EE FW Möllendorf\',\'Stadt Sonnewalde\',\'Landkreis Elbe-Elster\'),
        (621514,\'15\',62,\'EE FW Münchhausen\',\'Stadt Sonnewalde\',\'Landkreis Elbe-Elster\'),
        (621515,\'15\',62,\'EE FW Ossak\',\'Stadt Sonnewalde\',\'Landkreis Elbe-Elster\'),
        (621516,\'15\',62,\'EE FW Pahlsdorf\',\'Stadt Sonnewalde\',\'Landkreis Elbe-Elster\'),
        (621517,\'15\',62,\'EE FW Pießig\',\'Stadt Sonnewalde\',\'Landkreis Elbe-Elster\'),
        (621518,\'15\',62,\'EE FW Schönewalde (Fi)\',\'Stadt Sonnewalde\',\'Landkreis Elbe-Elster\'),
        (621519,\'15\',62,\'EE FW Zeckerin\',\'Stadt Sonnewalde\',\'Landkreis Elbe-Elster\'),
        (621602,\'16\',62,\'EE FW Bahnsdorf\',\'Stadt Uebigau/Wahrenbrück\',\'Landkreis Elbe-Elster\'),
        (621603,\'16\',62,\'EE FW Beiersdorf\',\'Stadt Uebigau/Wahrenbrück\',\'Landkreis Elbe-Elster\'),
        (621604,\'16\',62,\'EE FW Beutersitz\',\'Stadt Uebigau/Wahrenbrück\',\'Landkreis Elbe-Elster\'),
        (621605,\'16\',62,\'EE FW Bomsdorf\',\'Stadt Uebigau/Wahrenbrück\',\'Landkreis Elbe-Elster\'),
        (621606,\'16\',62,\'EE FW Domsdorf\',\'Stadt Uebigau/Wahrenbrück\',\'Landkreis Elbe-Elster\'),
        (621607,\'16\',62,\'EE FW Drasdo\',\'Stadt Uebigau/Wahrenbrück\',\'Landkreis Elbe-Elster\'),
        (621608,\'16\',62,\'EE FW Langennaundorf\',\'Stadt Uebigau/Wahrenbrück\',\'Landkreis Elbe-Elster\'),
        (621609,\'16\',62,\'EE FW Marxdorf\',\'Stadt Uebigau/Wahrenbrück\',\'Landkreis Elbe-Elster\'),
        (621610,\'16\',62,\'EE FW Prestewitz\',\'Stadt Uebigau/Wahrenbrück\',\'Landkreis Elbe-Elster\'),
        (621611,\'16\',62,\'EE FW Saxdorf\',\'Stadt Uebigau/Wahrenbrück\',\'Landkreis Elbe-Elster\'),
        (621612,\'16\',62,\'EE FW Uebigau\',\'Stadt Uebigau/Wahrenbrück\',\'Landkreis Elbe-Elster\'),
        (621613,\'16\',62,\'EE FW Wahrenbrück\',\'Stadt Uebigau/Wahrenbrück\',\'Landkreis Elbe-Elster\'),
        (621614,\'16\',62,\'EE FW Wiederau\',\'Stadt Uebigau/Wahrenbrück\',\'Landkreis Elbe-Elster\'),
        (621615,\'16\',62,\'EE FW Wildgrube\',\'Stadt Uebigau/Wahrenbrück\',\'Landkreis Elbe-Elster\'),
        (621616,\'16\',62,\'EE FW Winkel\',\'Stadt Uebigau/Wahrenbrück\',\'Landkreis Elbe-Elster\'),
        (621617,\'16\',62,\'EE FW Zinsdorf\',\'Stadt Uebigau/Wahrenbrück\',\'Landkreis Elbe-Elster\'),
        (629001,\'90\',62,\'EE RW Bad Liebenwerda\',\'Rettungswachen Elbe-Elster\',\'Landkreis Elbe-Elster\'),
        (629002,\'90\',62,\'EE RW Elsterwerda\',\'Rettungswachen Elbe-Elster\',\'Landkreis Elbe-Elster\'),
        (629003,\'90\',62,\'EE RW Finsterwalde\',\'Rettungswachen Elbe-Elster\',\'Landkreis Elbe-Elster\'),
        (629004,\'90\',62,\'EE RW Doberlug-Kirchhain\',\'Rettungswachen Elbe-Elster\',\'Landkreis Elbe-Elster\'),
        (629007,\'90\',62,\'EE RW Herzberg\',\'Rettungswachen Elbe-Elster\',\'Landkreis Elbe-Elster\'),
        (629009,\'90\',62,\'EE RW Weinberge\',\'Rettungswachen Elbe-Elster\',\'Landkreis Elbe-Elster\'),
        (629012,\'90\',62,\'EE RW Werchau\',\'Rettungswachen Elbe-Elster\',\'Landkreis Elbe-Elster\'),
        (629014,\'90\',62,\'EE RW Großthiemig\',\'Rettungswachen Elbe-Elster\',\'Landkreis Elbe-Elster\'),
        (629015,\'90\',62,\'EE RW Sonnewalde\',\'Rettungswachen Elbe-Elster\',\'Landkreis Elbe-Elster\'),
        (629016,\'90\',62,\'EE RW Uebigau / Wahrenbrück\',\'Rettungswachen Elbe-Elster\',\'Landkreis Elbe-Elster\'),
        (660101,\'01\',66,\'OSL FW Grünewalde\',\'Stadt Lauchhammer\',\'Landkreis Oberspreewald-Lausitz\'),
        (660102,\'01\',66,\'OSL FW Kostebrau\',\'Stadt Lauchhammer\',\'Landkreis Oberspreewald-Lausitz\'),
        (660103,\'01\',66,\'OSL FW Lauchhammer Mitte\',\'Stadt Lauchhammer\',\'Landkreis Oberspreewald-Lausitz\'),
        (660104,\'01\',66,\'OSL FW Lauchhammer West\',\'Stadt Lauchhammer\',\'Landkreis Oberspreewald-Lausitz\'),
        (660202,\'02\',66,\'OSL FW Schwarzheide Ost\',\'Stadt Schwarzheide\',\'Landkreis Oberspreewald-Lausitz\'),
        (660203,\'02\',66,\'OSL FW Schwarzheide West\',\'Stadt Schwarzheide\',\'Landkreis Oberspreewald-Lausitz\'),
        (660301,\'03\',66,\'OSL FW Brieske\',\'Stadt Senftenberg\',\'Landkreis Oberspreewald-Lausitz\'),
        (660302,\'03\',66,\'OSL FW Senftenberg FF\',\'Stadt Senftenberg\',\'Landkreis Oberspreewald-Lausitz\'),
        (660303,\'03\',66,\'OSL FW Großkoschen\',\'Stadt Senftenberg\',\'Landkreis Oberspreewald-Lausitz\'),
        (660304,\'03\',66,\'OSL FW Senftenberg HF\',\'Stadt Senftenberg\',\'Landkreis Oberspreewald-Lausitz\'),
        (660305,\'03\',66,\'OSL FW Hosena\',\'Stadt Senftenberg\',\'Landkreis Oberspreewald-Lausitz\'),
        (660306,\'03\',66,\'OSL FW Kleinkoschen\',\'Stadt Senftenberg\',\'Landkreis Oberspreewald-Lausitz\'),
        (660307,\'03\',66,\'OSL FW Niemtsch\',\'Stadt Senftenberg\',\'Landkreis Oberspreewald-Lausitz\'),
        (660308,\'03\',66,\'OSL FW Peickwitz\',\'Stadt Senftenberg\',\'Landkreis Oberspreewald-Lausitz\'),
        (660309,\'03\',66,\'OSL FW Sedlitz\',\'Stadt Senftenberg\',\'Landkreis Oberspreewald-Lausitz\'),
        (660401,\'04\',66,\'OSL FW Altdöbern\',\'Amt Altdöbern\',\'Landkreis Oberspreewald-Lausitz\'),
        (660402,\'04\',66,\'OSL FW Ranzow\',\'Amt Altdöbern\',\'Landkreis Oberspreewald-Lausitz\'),
        (660403,\'04\',66,\'OSL FW Reddern\',\'Amt Altdöbern\',\'Landkreis Oberspreewald-Lausitz\'),
        (660404,\'04\',66,\'OSL FW Bronkow\',\'Amt Altdöbern\',\'Landkreis Oberspreewald-Lausitz\'),
        (660405,\'04\',66,\'OSL FW Lipten\',\'Amt Altdöbern\',\'Landkreis Oberspreewald-Lausitz\'),
        (660406,\'04\',66,\'OSL FW Lug\',\'Amt Altdöbern\',\'Landkreis Oberspreewald-Lausitz\'),
        (660407,\'04\',66,\'OSL FW Rutzkau\',\'Amt Altdöbern\',\'Landkreis Oberspreewald-Lausitz\'),
        (660408,\'04\',66,\'OSL FW Saadow\',\'Amt Altdöbern\',\'Landkreis Oberspreewald-Lausitz\'),
        (660409,\'04\',66,\'OSL FW Buchwäldchen\',\'Amt Altdöbern\',\'Landkreis Oberspreewald-Lausitz\'),
        (660410,\'04\',66,\'OSL FW Gosda\',\'Amt Altdöbern\',\'Landkreis Oberspreewald-Lausitz\'),
        (660411,\'04\',66,\'OSL FW Muckwar\',\'Amt Altdöbern\',\'Landkreis Oberspreewald-Lausitz\'),
        (660412,\'04\',66,\'OSL FW Schöllnitz\',\'Amt Altdöbern\',\'Landkreis Oberspreewald-Lausitz\'),
        (660413,\'04\',66,\'OSL FW Bahnsdorf\',\'Amt Altdöbern\',\'Landkreis Oberspreewald-Lausitz\'),
        (660414,\'04\',66,\'OSL FW Lieske\',\'Amt Altdöbern\',\'Landkreis Oberspreewald-Lausitz\'),
        (660415,\'04\',66,\'OSL FW Lindchen\',\'Amt Altdöbern\',\'Landkreis Oberspreewald-Lausitz\'),
        (660416,\'04\',66,\'OSL FW Lubochow\',\'Amt Altdöbern\',\'Landkreis Oberspreewald-Lausitz\'),
        (660417,\'04\',66,\'OSL FW Ressen\',\'Amt Altdöbern\',\'Landkreis Oberspreewald-Lausitz\'),
        (660418,\'04\',66,\'OSL FW Neupetershain\',\'Amt Altdöbern\',\'Landkreis Oberspreewald-Lausitz\'),
        (660602,\'06\',66,\'OSL FW Calau\',\'Stadt Calau\',\'Landkreis Oberspreewald-Lausitz\'),
        (660603,\'06\',66,\'OSL FW Bathow\',\'Stadt Calau\',\'Landkreis Oberspreewald-Lausitz\'),
        (660604,\'06\',66,\'OSL FW Bolschwitz\',\'Stadt Calau\',\'Landkreis Oberspreewald-Lausitz\'),
        (660605,\'06\',66,\'OSL FW Buckow\',\'Stadt Calau\',\'Landkreis Oberspreewald-Lausitz\'),
        (660606,\'06\',66,\'OSL FW Cabel\',\'Stadt Calau\',\'Landkreis Oberspreewald-Lausitz\'),
        (660607,\'06\',66,\'OSL FW Craupe\',\'Stadt Calau\',\'Landkreis Oberspreewald-Lausitz\'),
        (660608,\'06\',66,\'OSL FW Gollmitz\',\'Stadt Calau\',\'Landkreis Oberspreewald-Lausitz\'),
        (660609,\'06\',66,\'OSL FW Groß Jehser\',\'Stadt Calau\',\'Landkreis Oberspreewald-Lausitz\'),
        (660610,\'06\',66,\'OSL FW Groß Mehßow\',\'Stadt Calau\',\'Landkreis Oberspreewald-Lausitz\'),
        (660611,\'06\',66,\'OSL FW Kalkwitz\',\'Stadt Calau\',\'Landkreis Oberspreewald-Lausitz\'),
        (660612,\'06\',66,\'OSL FW Kemmen\',\'Stadt Calau\',\'Landkreis Oberspreewald-Lausitz\'),
        (660613,\'06\',66,\'OSL FW Reuden\',\'Stadt Calau\',\'Landkreis Oberspreewald-Lausitz\'),
        (660614,\'06\',66,\'OSL FW Saßleben\',\'Stadt Calau\',\'Landkreis Oberspreewald-Lausitz\'),
        (660615,\'06\',66,\'OSL FW Werchow\',\'Stadt Calau\',\'Landkreis Oberspreewald-Lausitz\'),
        (660616,\'06\',66,\'OSL FW Zinnitz\',\'Stadt Calau\',\'Landkreis Oberspreewald-Lausitz\'),
        (660617,\'06\',66,\'OSL FW Mallenchen\',\'Stadt Calau\',\'Landkreis Oberspreewald-Lausitz\'),
        (660618,\'06\',66,\'OSL FW Klein Mehßow\',\'Stadt Calau\',\'Landkreis Oberspreewald-Lausitz\'),
        (660619,\'06\',66,\'OSL FW Säritz\',\'Stadt Calau\',\'Landkreis Oberspreewald-Lausitz\'),
        (660701,\'07\',66,\'OSL FW Allmosen\',\'Stadt Großräschen\',\'Landkreis Oberspreewald-Lausitz\'),
        (660702,\'07\',66,\'OSL FW Barzig\',\'Stadt Großräschen\',\'Landkreis Oberspreewald-Lausitz\'),
        (660703,\'07\',66,\'OSL FW Dörrwalde\',\'Stadt Großräschen\',\'Landkreis Oberspreewald-Lausitz\'),
        (660704,\'07\',66,\'OSL FW Freienhufen\',\'Stadt Großräschen\',\'Landkreis Oberspreewald-Lausitz\'),
        (660705,\'07\',66,\'OSL FW Großräschen Nord\',\'Stadt Großräschen\',\'Landkreis Oberspreewald-Lausitz\'),
        (660706,\'07\',66,\'OSL FW Großräschen Ost\',\'Stadt Großräschen\',\'Landkreis Oberspreewald-Lausitz\'),
        (660707,\'07\',66,\'OSL FW Saalhausen\',\'Stadt Großräschen\',\'Landkreis Oberspreewald-Lausitz\'),
        (660708,\'07\',66,\'OSL FW Wormlage\',\'Stadt Großräschen\',\'Landkreis Oberspreewald-Lausitz\'),
        (660709,\'07\',66,\'OSL FW Woschkow\',\'Stadt Großräschen\',\'Landkreis Oberspreewald-Lausitz\'),
        (660801,\'08\',66,\'OSL FW Lübbenau Altstadt\',\'Stadt Lübbenau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (660802,\'08\',66,\'OSL FW Bischdorf\',\'Stadt Lübbenau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (660803,\'08\',66,\'OSL FW Boblitz\',\'Stadt Lübbenau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (660804,\'08\',66,\'OSL FW Groß Beuchow\',\'Stadt Lübbenau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (660805,\'08\',66,\'OSL FW Groß Klessow\',\'Stadt Lübbenau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (660806,\'08\',66,\'OSL FW Groß Lübbenau\',\'Stadt Lübbenau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (660807,\'08\',66,\'OSL FW Groß Radden\',\'Stadt Lübbenau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (660808,\'08\',66,\'OSL FW Hindenberg\',\'Stadt Lübbenau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (660809,\'08\',66,\'OSL FW Kittlitz\',\'Stadt Lübbenau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (660810,\'08\',66,\'OSL FW Klein Radden\',\'Stadt Lübbenau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (660811,\'08\',66,\'OSL FW Krimnitz\',\'Stadt Lübbenau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (660812,\'08\',66,\'OSL FW Lehde\',\'Stadt Lübbenau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (660813,\'08\',66,\'OSL FW Leipe\',\'Stadt Lübbenau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (660814,\'08\',66,\'OSL FW Lübbenau Neustadt\',\'Stadt Lübbenau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (660815,\'08\',66,\'OSL FW Ragow\',\'Stadt Lübbenau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (660816,\'08\',66,\'OSL FW Zerkwitz\',\'Stadt Lübbenau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (660902,\'09\',66,\'OSL FW Großkmehlen\',\'Amt Ortrand\',\'Landkreis Oberspreewald-Lausitz\'),
        (660903,\'09\',66,\'OSL FW Frauwalde\',\'Amt Ortrand\',\'Landkreis Oberspreewald-Lausitz\'),
        (660904,\'09\',66,\'OSL FW Kleinkmehlen\',\'Amt Ortrand\',\'Landkreis Oberspreewald-Lausitz\'),
        (660905,\'09\',66,\'OSL FW Kroppen\',\'Amt Ortrand\',\'Landkreis Oberspreewald-Lausitz\'),
        (660906,\'09\',66,\'OSL FW Lindenau\',\'Amt Ortrand\',\'Landkreis Oberspreewald-Lausitz\'),
        (660907,\'09\',66,\'OSL FW Ortrand\',\'Amt Ortrand\',\'Landkreis Oberspreewald-Lausitz\'),
        (660908,\'09\',66,\'OSL FW Frauendorf\',\'Amt Ortrand\',\'Landkreis Oberspreewald-Lausitz\'),
        (660909,\'09\',66,\'OSL FW Tettau\',\'Amt Ortrand\',\'Landkreis Oberspreewald-Lausitz\'),
        (661002,\'10\',66,\'OSL FW Grünewald\',\'Amt Ruhland\',\'Landkreis Oberspreewald-Lausitz\'),
        (661003,\'10\',66,\'OSL FW Sella\',\'Amt Ruhland\',\'Landkreis Oberspreewald-Lausitz\'),
        (661004,\'10\',66,\'OSL FW Guteborn\',\'Amt Ruhland\',\'Landkreis Oberspreewald-Lausitz\'),
        (661005,\'10\',66,\'OSL FW Hermsdorf\',\'Amt Ruhland\',\'Landkreis Oberspreewald-Lausitz\'),
        (661006,\'10\',66,\'OSL FW Jannowitz\',\'Amt Ruhland\',\'Landkreis Oberspreewald-Lausitz\'),
        (661007,\'10\',66,\'OSL FW Lipsa\',\'Amt Ruhland\',\'Landkreis Oberspreewald-Lausitz\'),
        (661008,\'10\',66,\'OSL FW Hohenbocka\',\'Amt Ruhland\',\'Landkreis Oberspreewald-Lausitz\'),
        (661009,\'10\',66,\'OSL FW Ruhland\',\'Amt Ruhland\',\'Landkreis Oberspreewald-Lausitz\'),
        (661010,\'10\',66,\'OSL FW Arnsdorf\',\'Amt Ruhland\',\'Landkreis Oberspreewald-Lausitz\'),
        (661011,\'10\',66,\'OSL FW Schwarzbach\',\'Amt Ruhland\',\'Landkreis Oberspreewald-Lausitz\'),
        (661012,\'10\',66,\'OSL FW Biehlen\',\'Amt Ruhland\',\'Landkreis Oberspreewald-Lausitz\'),
        (661101,\'11\',66,\'OSL FW Schipkau\',\'Gemeinde Schipkau\',\'Landkreis Oberspreewald-Lausitz\'),
        (661102,\'11\',66,\'OSL FW Annahütte\',\'Gemeinde Schipkau\',\'Landkreis Oberspreewald-Lausitz\'),
        (661103,\'11\',66,\'OSL FW Drochow\',\'Gemeinde Schipkau\',\'Landkreis Oberspreewald-Lausitz\'),
        (661104,\'11\',66,\'OSL FW Hörlitz\',\'Gemeinde Schipkau\',\'Landkreis Oberspreewald-Lausitz\'),
        (661105,\'11\',66,\'OSL FW Klettwitz\',\'Gemeinde Schipkau\',\'Landkreis Oberspreewald-Lausitz\'),
        (661106,\'11\',66,\'OSL FW Meuro\',\'Gemeinde Schipkau\',\'Landkreis Oberspreewald-Lausitz\'),
        (661201,\'12\',66,\'OSL FW Vetschau\',\'Stadt Vetschau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (661202,\'12\',66,\'OSL FW Fleißdorf\',\'Stadt Vetschau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (661203,\'12\',66,\'OSL FW Gahlen\',\'Stadt Vetschau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (661204,\'12\',66,\'OSL FW Göritz\',\'Stadt Vetschau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (661205,\'12\',66,\'OSL FW Koßwig\',\'Stadt Vetschau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (661206,\'12\',66,\'OSL FW Laasow\',\'Stadt Vetschau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (661207,\'12\',66,\'OSL FW Vetschau Märkischheide\',\'Stadt Vetschau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (661208,\'12\',66,\'OSL FW Missen\',\'Stadt Vetschau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (661209,\'12\',66,\'OSL FW Naundorf\',\'Stadt Vetschau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (661210,\'12\',66,\'OSL FW Ogrosen\',\'Stadt Vetschau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (661211,\'12\',66,\'OSL FW Raddusch\',\'Stadt Vetschau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (661212,\'12\',66,\'OSL FW Repten\',\'Stadt Vetschau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (661213,\'12\',66,\'OSL FW Stradow\',\'Stadt Vetschau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (661214,\'12\',66,\'OSL FW Suschow\',\'Stadt Vetschau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (661215,\'12\',66,\'OSL FW Wüstenhain\',\'Stadt Vetschau/Spreewald\',\'Landkreis Oberspreewald-Lausitz\'),
        (669001,\'90\',66,\'OSL RW Lauchhammer\',\'Rettungswachen Oberspreewald-Lausitz\',\'Landkreis Oberspreewald-Lausitz\'),
        (669003,\'90\',66,\'OSL RW Senftenberg\',\'Rettungswachen Oberspreewald-Lausitz\',\'Landkreis Oberspreewald-Lausitz\'),
        (669006,\'90\',66,\'OSL RW Calau\',\'Rettungswachen Oberspreewald-Lausitz\',\'Landkreis Oberspreewald-Lausitz\'),
        (669007,\'90\',66,\'OSL RW Großräschen\',\'Rettungswachen Oberspreewald-Lausitz\',\'Landkreis Oberspreewald-Lausitz\'),
        (669008,\'90\',66,\'OSL RW Lübbenau Neustadt\',\'Rettungswachen Oberspreewald-Lausitz\',\'Landkreis Oberspreewald-Lausitz\'),
        (669009,\'90\',66,\'OSL RW Lübbenau Altstadt\',\'Rettungswachen Oberspreewald-Lausitz\',\'Landkreis Oberspreewald-Lausitz\'),
        (669010,\'90\',66,\'OSL RW Jannowitz\',\'Rettungswachen Oberspreewald-Lausitz\',\'Landkreis Oberspreewald-Lausitz\'),
        (669012,\'90\',66,\'OSL RW Vetschau\',\'Rettungswachen Oberspreewald-Lausitz\',\'Landkreis Oberspreewald-Lausitz\'),
        (710101,\'01\',71,\'SPN FW Forst\',\'Stadt Forst\',\'Landkreis Spree-Neiße\'),
        (710102,\'01\',71,\'SPN FW Bohrau\',\'Stadt Forst\',\'Landkreis Spree-Neiße\'),
        (710103,\'01\',71,\'SPN FW Briesnig\',\'Stadt Forst\',\'Landkreis Spree-Neiße\'),
        (710104,\'01\',71,\'SPN FW Domsdorf\',\'Stadt Forst\',\'Landkreis Spree-Neiße\'),
        (710105,\'01\',71,\'SPN FW Eulo\',\'Stadt Forst\',\'Landkreis Spree-Neiße\'),
        (710106,\'01\',71,\'SPN FW Groß Bademeusel\',\'Stadt Forst\',\'Landkreis Spree-Neiße\'),
        (710107,\'01\',71,\'SPN FW Groß Jamno\',\'Stadt Forst\',\'Landkreis Spree-Neiße\'),
        (710108,\'01\',71,\'SPN FW Horno\',\'Stadt Forst\',\'Landkreis Spree-Neiße\'),
        (710109,\'01\',71,\'SPN FW Klein Bademeusel\',\'Stadt Forst\',\'Landkreis Spree-Neiße\'),
        (710110,\'01\',71,\'SPN FW Mulknitz\',\'Stadt Forst\',\'Landkreis Spree-Neiße\'),
        (710111,\'01\',71,\'SPN FW Naundorf\',\'Stadt Forst\',\'Landkreis Spree-Neiße\'),
        (710112,\'01\',71,\'SPN FW Sacro\',\'Stadt Forst\',\'Landkreis Spree-Neiße\'),
        (710113,\'01\',71,\'SPN FW Forst Süd\',\'Stadt Forst\',\'Landkreis Spree-Neiße\'),
        (710201,\'02\',71,\'SPN FW Guben\',\'Stadt Guben\',\'Landkreis Spree-Neiße\'),
        (710202,\'02\',71,\'SPN FW Bresinchen\',\'Stadt Guben\',\'Landkreis Spree-Neiße\'),
        (710203,\'02\',71,\'SPN FW Groß Breesen\',\'Stadt Guben\',\'Landkreis Spree-Neiße\'),
        (710204,\'02\',71,\'SPN FW Kaltenborn\',\'Stadt Guben\',\'Landkreis Spree-Neiße\'),
        (710205,\'02\',71,\'SPN FW Reichenbach\',\'Stadt Guben\',\'Landkreis Spree-Neiße\'),
        (710206,\'02\',71,\'SPN FW Schlagsdorf\',\'Stadt Guben\',\'Landkreis Spree-Neiße\'),
        (710302,\'03\',71,\'SPN FW Kolkwitz\',\'Gemeinde Kolkwitz\',\'Landkreis Spree-Neiße\'),
        (710303,\'03\',71,\'SPN FW Babow\',\'Gemeinde Kolkwitz\',\'Landkreis Spree-Neiße\'),
        (710304,\'03\',71,\'SPN FW Brodtkowitz\',\'Gemeinde Kolkwitz\',\'Landkreis Spree-Neiße\'),
        (710305,\'03\',71,\'SPN FW Dahlitz\',\'Gemeinde Kolkwitz\',\'Landkreis Spree-Neiße\'),
        (710306,\'03\',71,\'SPN FW Eichow\',\'Gemeinde Kolkwitz\',\'Landkreis Spree-Neiße\'),
        (710307,\'03\',71,\'SPN FW Glinzig\',\'Gemeinde Kolkwitz\',\'Landkreis Spree-Neiße\'),
        (710308,\'03\',71,\'SPN FW Gulben\',\'Gemeinde Kolkwitz\',\'Landkreis Spree-Neiße\'),
        (710309,\'03\',71,\'SPN FW Hänchen\',\'Gemeinde Kolkwitz\',\'Landkreis Spree-Neiße\'),
        (710310,\'03\',71,\'SPN FW Kackrow\',\'Gemeinde Kolkwitz\',\'Landkreis Spree-Neiße\'),
        (710311,\'03\',71,\'SPN FW Klein Gaglow\',\'Gemeinde Kolkwitz\',\'Landkreis Spree-Neiße\'),
        (710312,\'03\',71,\'SPN FW Krieschow\',\'Gemeinde Kolkwitz\',\'Landkreis Spree-Neiße\'),
        (710313,\'03\',71,\'SPN FW Kunersdorf\',\'Gemeinde Kolkwitz\',\'Landkreis Spree-Neiße\'),
        (710314,\'03\',71,\'SPN FW Limberg\',\'Gemeinde Kolkwitz\',\'Landkreis Spree-Neiße\'),
        (710315,\'03\',71,\'SPN FW Milkersdorf\',\'Gemeinde Kolkwitz\',\'Landkreis Spree-Neiße\'),
        (710316,\'03\',71,\'SPN FW Papitz\',\'Gemeinde Kolkwitz\',\'Landkreis Spree-Neiße\'),
        (710317,\'03\',71,\'SPN FW Wiesendorf\',\'Gemeinde Kolkwitz\',\'Landkreis Spree-Neiße\'),
        (710318,\'03\',71,\'SPN FW Zahsow\',\'Gemeinde Kolkwitz\',\'Landkreis Spree-Neiße\'),
        (710402,\'04\',71,\'SPN FW Spremberg\',\'Stadt Spremberg\',\'Landkreis Spree-Neiße\'),
        (710403,\'04\',71,\'SPN FW Bühlow\',\'Stadt Spremberg\',\'Landkreis Spree-Neiße\'),
        (710404,\'04\',71,\'SPN FW Graustein\',\'Stadt Spremberg\',\'Landkreis Spree-Neiße\'),
        (710405,\'04\',71,\'SPN FW Groß Luja\',\'Stadt Spremberg\',\'Landkreis Spree-Neiße\'),
        (710406,\'04\',71,\'SPN FW Haidemühl\',\'Stadt Spremberg\',\'Landkreis Spree-Neiße\'),
        (710407,\'04\',71,\'SPN FW Lieskau\',\'Stadt Spremberg\',\'Landkreis Spree-Neiße\'),
        (710408,\'04\',71,\'SPN FW Schönheide\',\'Stadt Spremberg\',\'Landkreis Spree-Neiße\'),
        (710409,\'04\',71,\'SPN FW Schwarze Pumpe\',\'Stadt Spremberg\',\'Landkreis Spree-Neiße\'),
        (710410,\'04\',71,\'SPN FW Sellessen\',\'Stadt Spremberg\',\'Landkreis Spree-Neiße\'),
        (710411,\'04\',71,\'SPN FW Terpe\',\'Stadt Spremberg\',\'Landkreis Spree-Neiße\'),
        (710412,\'04\',71,\'SPN FW Türkendorf\',\'Stadt Spremberg\',\'Landkreis Spree-Neiße\'),
        (710413,\'04\',71,\'SPN FW Weskow\',\'Stadt Spremberg\',\'Landkreis Spree-Neiße\'),
        (710502,\'05\',71,\'SPN FW Briesen\',\'Amt Burg (Spreewald)\',\'Landkreis Spree-Neiße\'),
        (710503,\'05\',71,\'SPN FW Burg\',\'Amt Burg (Spreewald)\',\'Landkreis Spree-Neiße\'),
        (710504,\'05\',71,\'SPN FW Burg Kolonie\',\'Amt Burg (Spreewald)\',\'Landkreis Spree-Neiße\'),
        (710505,\'05\',71,\'SPN FW Müschen\',\'Amt Burg (Spreewald)\',\'Landkreis Spree-Neiße\'),
        (710506,\'05\',71,\'SPN FW Burg Kauper\',\'Amt Burg (Spreewald)\',\'Landkreis Spree-Neiße\'),
        (710507,\'05\',71,\'SPN FW Dissen\',\'Amt Burg (Spreewald)\',\'Landkreis Spree-Neiße\'),
        (710508,\'05\',71,\'SPN FW Striesow\',\'Amt Burg (Spreewald)\',\'Landkreis Spree-Neiße\'),
        (710509,\'05\',71,\'SPN FW Guhrow\',\'Amt Burg (Spreewald)\',\'Landkreis Spree-Neiße\'),
        (710510,\'05\',71,\'SPN FW Schmogrow\',\'Amt Burg (Spreewald)\',\'Landkreis Spree-Neiße\'),
        (710511,\'05\',71,\'SPN FW Fehrow\',\'Amt Burg (Spreewald)\',\'Landkreis Spree-Neiße\'),
        (710512,\'05\',71,\'SPN FW Werben\',\'Amt Burg (Spreewald)\',\'Landkreis Spree-Neiße\'),
        (710513,\'05\',71,\'SPN FW Ruben\',\'Amt Burg (Spreewald)\',\'Landkreis Spree-Neiße\'),
        (710602,\'06\',71,\'SPN FW Döbern\',\'Amt Döbern-Land\',\'Landkreis Spree-Neiße\'),
        (710603,\'06\',71,\'SPN FW Eichwege\',\'Amt Döbern-Land\',\'Landkreis Spree-Neiße\'),
        (710604,\'06\',71,\'SPN FW Bloischdorf\',\'Amt Döbern-Land\',\'Landkreis Spree-Neiße\'),
        (710605,\'06\',71,\'SPN FW Bohsdorf\',\'Amt Döbern-Land\',\'Landkreis Spree-Neiße\'),
        (710606,\'06\',71,\'SPN FW Friedrichshain\',\'Amt Döbern-Land\',\'Landkreis Spree-Neiße\'),
        (710607,\'06\',71,\'SPN FW Klein Loitz\',\'Amt Döbern-Land\',\'Landkreis Spree-Neiße\'),
        (710608,\'06\',71,\'SPN FW Reuthen\',\'Amt Döbern-Land\',\'Landkreis Spree-Neiße\'),
        (710609,\'06\',71,\'SPN FW Groß Schacksdorf\',\'Amt Döbern-Land\',\'Landkreis Spree-Neiße\'),
        (710611,\'06\',71,\'SPN FW Hornow\',\'Amt Döbern-Land\',\'Landkreis Spree-Neiße\'),
        (710612,\'06\',71,\'SPN FW Wadelsdorf\',\'Amt Döbern-Land\',\'Landkreis Spree-Neiße\'),
        (710613,\'06\',71,\'SPN FW Jämlitz\',\'Amt Döbern-Land\',\'Landkreis Spree-Neiße\'),
        (710614,\'06\',71,\'SPN FW Klein Düben\',\'Amt Döbern-Land\',\'Landkreis Spree-Neiße\'),
        (710615,\'06\',71,\'SPN FW Gosda 2\',\'Amt Döbern-Land\',\'Landkreis Spree-Neiße\'),
        (710616,\'06\',71,\'SPN FW Groß Kölzig\',\'Amt Döbern-Land\',\'Landkreis Spree-Neiße\'),
        (710617,\'06\',71,\'SPN FW Jerischke\',\'Amt Döbern-Land\',\'Landkreis Spree-Neiße\'),
        (710618,\'06\',71,\'SPN FW Jocksdorf\',\'Amt Döbern-Land\',\'Landkreis Spree-Neiße\'),
        (710619,\'06\',71,\'SPN FW Klein Kölzig\',\'Amt Döbern-Land\',\'Landkreis Spree-Neiße\'),
        (710620,\'06\',71,\'SPN FW Preschen\',\'Amt Döbern-Land\',\'Landkreis Spree-Neiße\'),
        (710621,\'06\',71,\'SPN FW Tschernitz\',\'Amt Döbern-Land\',\'Landkreis Spree-Neiße\'),
        (710622,\'06\',71,\'SPN FW Wolfshain\',\'Amt Döbern-Land\',\'Landkreis Spree-Neiße\'),
        (710623,\'06\',71,\'SPN FW Dubrau\',\'Amt Döbern-Land\',\'Landkreis Spree-Neiße\'),
        (710624,\'06\',71,\'SPN FW Gahry\',\'Amt Döbern-Land\',\'Landkreis Spree-Neiße\'),
        (710625,\'06\',71,\'SPN FW Gosda 1\',\'Amt Döbern-Land\',\'Landkreis Spree-Neiße\'),
        (710626,\'06\',71,\'SPN FW Jethe\',\'Amt Döbern-Land\',\'Landkreis Spree-Neiße\'),
        (710627,\'06\',71,\'SPN FW Mattendorf\',\'Amt Döbern-Land\',\'Landkreis Spree-Neiße\'),
        (710628,\'06\',71,\'SPN FW Trebendorf\',\'Amt Döbern-Land\',\'Landkreis Spree-Neiße\'),
        (710701,\'07\',71,\'SPN FW Drebkau\',\'Stadt Drebkau\',\'Landkreis Spree-Neiße\'),
        (710702,\'07\',71,\'SPN FW Casel\',\'Stadt Drebkau\',\'Landkreis Spree-Neiße\'),
        (710703,\'07\',71,\'SPN FW Greifenhain\',\'Stadt Drebkau\',\'Landkreis Spree-Neiße\'),
        (710704,\'07\',71,\'SPN FW Jehserig\',\'Stadt Drebkau\',\'Landkreis Spree-Neiße\'),
        (710705,\'07\',71,\'SPN FW Laubst\',\'Stadt Drebkau\',\'Landkreis Spree-Neiße\'),
        (710706,\'07\',71,\'SPN FW Leuthen\',\'Stadt Drebkau\',\'Landkreis Spree-Neiße\'),
        (710707,\'07\',71,\'SPN FW Löschen\',\'Stadt Drebkau\',\'Landkreis Spree-Neiße\'),
        (710708,\'07\',71,\'SPN FW Schorbus\',\'Stadt Drebkau\',\'Landkreis Spree-Neiße\'),
        (710709,\'07\',71,\'SPN FW Siewisch\',\'Stadt Drebkau\',\'Landkreis Spree-Neiße\'),
        (710710,\'07\',71,\'SPN FW Steinitz\',\'Stadt Drebkau\',\'Landkreis Spree-Neiße\'),
        (711002,\'10\',71,\'SPN FW Neuhausen/Spree\',\'Gemeinde Neuhausen/Spree\',\'Landkreis Spree-Neiße\'),
        (711003,\'10\',71,\'SPN FW Bagenz\',\'Gemeinde Neuhausen/Spree\',\'Landkreis Spree-Neiße\'),
        (711004,\'10\',71,\'SPN FW Drieschnitz\',\'Gemeinde Neuhausen/Spree\',\'Landkreis Spree-Neiße\'),
        (711005,\'10\',71,\'SPN FW Frauendorf\',\'Gemeinde Neuhausen/Spree\',\'Landkreis Spree-Neiße\'),
        (711006,\'10\',71,\'SPN FW Gablenz\',\'Gemeinde Neuhausen/Spree\',\'Landkreis Spree-Neiße\'),
        (711007,\'10\',71,\'SPN FW Groß Döbbern\',\'Gemeinde Neuhausen/Spree\',\'Landkreis Spree-Neiße\'),
        (711008,\'10\',71,\'SPN FW Groß Oßnig\',\'Gemeinde Neuhausen/Spree\',\'Landkreis Spree-Neiße\'),
        (711009,\'10\',71,\'SPN FW Haasow\',\'Gemeinde Neuhausen/Spree\',\'Landkreis Spree-Neiße\'),
        (711010,\'10\',71,\'SPN FW Kahsel\',\'Gemeinde Neuhausen/Spree\',\'Landkreis Spree-Neiße\'),
        (711011,\'10\',71,\'SPN FW Kathlow\',\'Gemeinde Neuhausen/Spree\',\'Landkreis Spree-Neiße\'),
        (711012,\'10\',71,\'SPN FW Klein Döbbern\',\'Gemeinde Neuhausen/Spree\',\'Landkreis Spree-Neiße\'),
        (711013,\'10\',71,\'SPN FW Komptendorf\',\'Gemeinde Neuhausen/Spree\',\'Landkreis Spree-Neiße\'),
        (711014,\'10\',71,\'SPN FW Koppatz\',\'Gemeinde Neuhausen/Spree\',\'Landkreis Spree-Neiße\'),
        (711015,\'10\',71,\'SPN FW Laubsdorf\',\'Gemeinde Neuhausen/Spree\',\'Landkreis Spree-Neiße\'),
        (711016,\'10\',71,\'SPN FW Roggosen\',\'Gemeinde Neuhausen/Spree\',\'Landkreis Spree-Neiße\'),
        (711017,\'10\',71,\'SPN FW Sergen\',\'Gemeinde Neuhausen/Spree\',\'Landkreis Spree-Neiße\'),
        (711102,\'11\',71,\'SPN FW Drachhausen\',\'Amt Peitz\',\'Landkreis Spree-Neiße\'),
        (711103,\'11\',71,\'SPN FW Drehnow\',\'Amt Peitz\',\'Landkreis Spree-Neiße\'),
        (711104,\'11\',71,\'SPN FW Heinersbrück\',\'Amt Peitz\',\'Landkreis Spree-Neiße\'),
        (711105,\'11\',71,\'SPN FW Grötsch\',\'Amt Peitz\',\'Landkreis Spree-Neiße\'),
        (711106,\'11\',71,\'SPN FW Radewiese\',\'Amt Peitz\',\'Landkreis Spree-Neiße\'),
        (711107,\'11\',71,\'SPN FW Jänschwalde\',\'Amt Peitz\',\'Landkreis Spree-Neiße\'),
        (711108,\'11\',71,\'SPN FW Drewitz\',\'Amt Peitz\',\'Landkreis Spree-Neiße\'),
        (711109,\'11\',71,\'SPN FW Grießen\',\'Amt Peitz\',\'Landkreis Spree-Neiße\'),
        (711110,\'11\',71,\'SPN FW Peitz\',\'Amt Peitz\',\'Landkreis Spree-Neiße\'),
        (711111,\'11\',71,\'SPN FW Tauer\',\'Amt Peitz\',\'Landkreis Spree-Neiße\'),
        (711113,\'11\',71,\'SPN FW Bärenbrück\',\'Amt Peitz\',\'Landkreis Spree-Neiße\'),
        (711114,\'11\',71,\'SPN FW Maust\',\'Amt Peitz\',\'Landkreis Spree-Neiße\'),
        (711115,\'11\',71,\'SPN FW Neuendorf\',\'Amt Peitz\',\'Landkreis Spree-Neiße\'),
        (711116,\'11\',71,\'SPN FW Preilack\',\'Amt Peitz\',\'Landkreis Spree-Neiße\'),
        (711117,\'11\',71,\'SPN FW Turnow\',\'Amt Peitz\',\'Landkreis Spree-Neiße\'),
        (711202,\'12\',71,\'SPN FW Schenkendöbern\',\'Gemeinde Schenkendöbern\',\'Landkreis Spree-Neiße\'),
        (711203,\'12\',71,\'SPN FW Atterwasch\',\'Gemeinde Schenkendöbern\',\'Landkreis Spree-Neiße\'),
        (711204,\'12\',71,\'SPN FW Grabko\',\'Gemeinde Schenkendöbern\',\'Landkreis Spree-Neiße\'),
        (711205,\'12\',71,\'SPN FW Grano\',\'Gemeinde Schenkendöbern\',\'Landkreis Spree-Neiße\'),
        (711206,\'12\',71,\'SPN FW Groß Drewitz\',\'Gemeinde Schenkendöbern\',\'Landkreis Spree-Neiße\'),
        (711207,\'12\',71,\'SPN FW Groß Gastrose\',\'Gemeinde Schenkendöbern\',\'Landkreis Spree-Neiße\'),
        (711208,\'12\',71,\'SPN FW Kerkwitz\',\'Gemeinde Schenkendöbern\',\'Landkreis Spree-Neiße\'),
        (711209,\'12\',71,\'SPN FW Krayne\',\'Gemeinde Schenkendöbern\',\'Landkreis Spree-Neiße\'),
        (711210,\'12\',71,\'SPN FW Lauschütz\',\'Gemeinde Schenkendöbern\',\'Landkreis Spree-Neiße\'),
        (711211,\'12\',71,\'SPN FW Lübbinchen\',\'Gemeinde Schenkendöbern\',\'Landkreis Spree-Neiße\'),
        (711212,\'12\',71,\'SPN FW Pinnow\',\'Gemeinde Schenkendöbern\',\'Landkreis Spree-Neiße\'),
        (711213,\'12\',71,\'SPN FW Reicherskreuz\',\'Gemeinde Schenkendöbern\',\'Landkreis Spree-Neiße\'),
        (711214,\'12\',71,\'SPN FW Sembten\',\'Gemeinde Schenkendöbern\',\'Landkreis Spree-Neiße\'),
        (711216,\'12\',71,\'SPN FW Taubendorf\',\'Gemeinde Schenkendöbern\',\'Landkreis Spree-Neiße\'),
        (711302,\'13\',71,\'SPN FW Welzow\',\'Stadt Welzow\',\'Landkreis Spree-Neiße\'),
        (711303,\'13\',71,\'SPN FW Proschim\',\'Stadt Welzow\',\'Landkreis Spree-Neiße\'),
        (719001,\'90\',71,\'SPN RW Forst\',\'Rettungswachen Spree-Neiße\',\'Landkreis Spree-Neiße\'),
        (719002,\'90\',71,\'SPN RW Guben\',\'Rettungswachen Spree-Neiße\',\'Landkreis Spree-Neiße\'),
        (719003,\'90\',71,\'SPN RW Burg FR\',\'Rettungswachen Spree-Neiße\',\'Landkreis Spree-Neiße\'),
        (719004,\'90\',71,\'SPN RW Spremberg\',\'Rettungswachen Spree-Neiße\',\'Landkreis Spree-Neiße\'),
        (719005,\'90\',71,\'SPN RW Burg\',\'Rettungswachen Spree-Neiße\',\'Landkreis Spree-Neiße\'),
        (719006,\'90\',71,\'SPN RW Döbern\',\'Rettungswachen Spree-Neiße\',\'Landkreis Spree-Neiße\'),
        (719007,\'90\',71,\'SPN RW Drebkau\',\'Rettungswachen Spree-Neiße\',\'Landkreis Spree-Neiße\'),
        (719011,\'90\',71,\'SPN RW Peitz\',\'Rettungswachen Spree-Neiße\',\'Landkreis Spree-Neiße\')`);
      // TTS-Ersetzungen  mit Standardwerten befuellen
      db.run(`INSERT OR REPLACE INTO waip_ttsreplace (
        einsatzmittel_typ, einsatzmittel_rufname)
        VALUES
        (\'10\',\'ELW\'),
        (\'11\',\'ELW\'),
        (\'14\',\'KDOW\'),
        (\'19\',\'MTW\'),
        (\'20\',\'Tanklöschfahrzeug\'),
        (\'21\',\'Tanklöschfahrzeug\'),
        (\'22\',\'Tanklöschfahrzeug\'),
        (\'23\',\'Tanklöschfahrzeug\'),
        (\'24\',\'Tanklöschfahrzeug\'),
        (\'25\',\'Tanklöschfahrzeug\'),
        (\'30\',\'Drehleiter\'),
        (\'31\',\'Drehleiter\'),
        (\'32\',\'Drehleiter\'),
        (\'33\',\'Drehleiter\'),
        (\'34\',\'Drehleiter\'),
        (\'35\',\'Drehleiter\'),
        (\'36\',\'Hubretter\'),
        (\'37\',\'Hubretter\'),
        (\'38\',\'Hubretter\'),
        (\'41\',\'Löschfahrzeug\'),
        (\'42\',\'Löschfahrzeug\'),
        (\'43\',\'HLF\'),
        (\'44\',\'Löschfahrzeug\'),
        (\'45\',\'Löschfahrzeug\'),
        (\'46\',\'HLF\'),
        (\'47\',\'TSF\'),
        (\'48\',\'TSF\'),
        (\'51\',\'Rüstwagen\'),
        (\'52\',\'Rüstwagen\'),
        (\'59\',\'Rüstwagen\'),
        (\'59\',\'Gerätewagen\'),
        (\'69\',\'TSA\'),
        (\'79\',\'Rettungsboot\'),
        (\'82\',\'NEF\'),
        (\'83\',\'RTW\'),
        (\'85\',\'KTW\'),
        (\'88\',\'Rettungsboot\')`);
      // Benutzer-Tabelle mit Standard befuellen
      db.get("SELECT user from waip_users", function(err, row) {
        if (!row) {
          /*bcrypt.hash('a', 1, function(err, hash) {
            console.log(hash);
          });*/
        };
      });
      /*bcrypt.hash(app_cfg.global.defaultpass, app_cfg.global.saltRounds, function(err, hash) {
        db.run(`INSERT INTO waip_users ( user, password, permissions ) VALUES( ?, ?, 'admin' )`, app_cfg.global.defaultuser, hash, function(err) {
          if (err) {
            console.log(err);
          };
        });
      });*/
    });
  };

  return db;

};
